services:
  ftp-server:
    image: 
    container_name: ftp_server
    ports:
      - "20"
      - "21"
    volumes:
      - ftp-data:/ftp/shared        
      - server-config:/app/config   
    networks:
      custom_net:
        ipv4_address: 172.24.0.2

  ssh-server:
    image: 
    container_name: ssh_server
    ports:
      - "22"
    volumes:
      - ssh-user:/home        
      - ssh-config:/etc/ssh   
    networks:
      custom_net:
        ipv4_address: 172.24.0.3

  client:
    image: 
    container_name: client
    depends_on:
      - ftp-server
      - ssh-server
    volumes:
      - client-data:/home
    networks:
      custom_net:
        ipv4_address: 172.24.0.4

volumes:
  ftp-data:
  server-config:
  client-config:
  ssh-user:        
  ssh-config:   
  client-data:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
