services:
  ftp-server:
    image: nicolassarmiento8/fedora-ftp:latest
    container_name: ftp_server
    ports:
      - "20"
      - "21"
    volumes:
      - ftp-data:/home         
    networks:
      private_network:
        ipv4_address: 172.24.0.2

  ssh-server:
    image: nicolassarmiento8/ssh-server:latest
    container_name: ssh_server
    ports:
      - "22"
    volumes:
      - ssh-user:/home        
      - ssh-config:/etc/ssh   
    networks:
      private_network:
        ipv4_address: 172.24.0.3

  client:
    image: nicolassarmiento8/client:latest
    container_name: client
    depends_on:
      - ftp-server
      - ssh-server
    volumes:
      - client-data:/home
    networks:
      private_network:
        ipv4_address: 172.24.0.4

volumes:
  ftp-data:
  client-config:
  ssh-user:        
  ssh-config:   
  client-data:

networks:
  private_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
